-- Drop the old dummy table
DROP TABLE IF EXISTS dummy;

-- ─── Property table ──────────────────────────────────────────────────────────
CREATE TABLE property (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  property_address text NOT NULL,
  property_type text,
  zoning text,
  municipality text,
  cadastre_reference text,
  year_built text,
  num_floors text,
  num_units_total text,
  unit_mix_description text,
  construction_frame text,
  foundation_type text,
  heating_type text,
  heating_fuel text,
  heating_num_units text,
  electrical_amperage text,
  electrical_panel_type text,
  electrical_network_type text,
  hot_water_tank_type text,
  hot_water_energy_source text,
  ac_type text,
  ac_num_units text,
  kitchen_cabinets text,
  kitchen_countertops text,
  kitchen_appliances text,
  amenity_central_vacuum text,
  amenity_fire_suppression text,
  amenity_intercoms text,
  amenity_elevator text,
  amenity_emergency_lighting text,
  amenity_exterior_lighting text,
  amenity_security_cameras text,
  amenity_other_common text,
  unit_balcony text,
  unit_washer_dryer_hookup text,
  unit_central_vacuum text,
  unit_ac text,
  unit_other_features text,
  parking_total_spaces text,
  parking_type text,
  parking_per_unit text,
  storage_lockers_num text,
  storage_lockers_type text,
  exterior_cladding text,
  roof_type text,
  window_type text,
  sqft_per_unit_habitable text,
  sqft_ground_floor text,
  sqft_upper_floors text,
  sqft_basement text,
  basement_finished_pct text,
  sqft_total_building text,
  lot_size_total text,
  lot_frontage text,
  lot_depth text,
  lot_configuration text,
  lot_topography text,
  lot_access text,
  municipal_services text,
  current_owner text,
  ownership_type text,
  permit_license_number text,
  construction_status text,
  appraised_value text,
  evaluation_date text,
  valuation_method text,
  value_per_unit text,
  value_per_sqft text,
  wall_finish text,
  ceiling_type text,
  flooring_living text,
  flooring_kitchen text,
  flooring_bathroom text,
  flooring_basement text,
  doors_exterior text,
  doors_interior text,
  bathrooms_per_unit text,
  bathroom_fixtures text,
  bathroom_vanity_finish text,
  bathroom_tub_shower_finish text,
  laundry_type text,
  laundry_location text,
  roof_material text,
  roof_remaining_life_yrs text,
  gutters_type text,
  cladding_condition text,
  windows_condition text,
  doors_condition text,
  fire_suppression_system text,
  fire_alarms text,
  sprinkler_system text,
  security_system text,
  security_cameras text,
  intercoms text,
  building_access_type text,
  building_code_compliance text,
  contamination_risk text,
  flood_risk text,
  soil_issues text,
  env_certifications text,
  structural_issues text,
  structural_issues_detail text,
  roof_issues text,
  roof_issues_detail text,
  plumbing_issues text,
  plumbing_issues_detail text,
  electrical_issues text,
  electrical_issues_detail text,
  hvac_issues text,
  hvac_issues_detail text,
  moisture_issues text,
  moisture_issues_detail text,
  other_maintenance_issues text,
  landscaping text,
  outdoor_amenities text,
  outdoor_utilities text,
  gross_potential_income_annual text,
  actual_rental_income_annual text,
  commercial_parking_revenue text,
  other_revenue text,
  total_revenue text,
  expense_property_taxes text,
  expense_school_taxes text,
  expense_insurance text,
  expense_utilities text,
  expense_maintenance text,
  expense_landscaping_snow text,
  expense_management text,
  expense_vacancy_bad_debt text,
  total_operating_expenses text,
  net_operating_income text,
  gross_rent_multiplier text,
  cap_rate text,
  debt_service_coverage_ratio text,
  operating_expense_ratio text,
  avg_rent_per_unit text,
  market_supply_demand text,
  market_price_trend text,
  avg_days_on_market text,
  num_comparables_used text,
  comparable_date_range text,
  comparable_price_range text,
  comparable_avg_price_per_unit text,
  major_renovations text,
  additions_modifications text,
  previous_sales text,
  easements text,
  restrictive_covenants text,
  servitudes text,
  special_assessments_pending text,
  special_assessment_amount text,
  reserve_fund_required text,
  reserve_fund_current text,
  reserve_fund_pct_funded text,
  deferred_maintenance_budget text,
  appraisal_notes text,
  source_file text,
  uploaded_at timestamptz DEFAULT now()
);

CREATE INDEX idx_property_address ON property (property_address);

-- ─── Unit table ──────────────────────────────────────────────────────────────
CREATE TABLE unit (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  property_id uuid NOT NULL REFERENCES property(id) ON DELETE CASCADE,
  unit_number text,
  unit_type text,
  beds text,
  baths text,
  sqft bigint,
  lease_rate double precision,
  move_in text,
  move_out text,
  source_file text,
  uploaded_at timestamptz DEFAULT now()
);

CREATE INDEX idx_unit_property_id ON unit (property_id);
